import type {
  AnnouncementItem,
  MarketCoin,
  PerkStep,
  ProfileSnapshot,
} from './types.js'

export const PROFILE_SNAPSHOT: ProfileSnapshot = {
  email: 'dem***@example.com',
  uid: 'DE****78',
  referralCode: 'DEMO2025',
  kycStatus: 'pending',
  signupAt: '15/06/2024 12:00 AM',
  lastLoginIp: '192.***.***.*0',
  vipLevel: 'VIP0',
  riskLevel: 'Low',
  verified: false,
  walletBalanceUsd: '7565811.83118268',
  walletBalanceBnb: '12703.69',
}

export const NEWCOMER_PERKS: PerkStep[] = [
  {
    step: 1,
    title: 'Verify identity and claim',
    highlight: '15 USDT',
    countdown: ['13D', '10', '12', '23'],
    ctaLabel: 'Verify Now',
    image: '/images/steps_vector.svg',
    active: true,
  },
  {
    step: 2,
    title: 'First Deposit',
    description: 'First deposit and boost your trading journey.',
    ctaLabel: 'Deposit Now',
    image: '/images/steps_vector2.svg',
  },
  {
    step: 3,
    title: 'Start Trading',
    description: 'Make your first trade and advanced trading features.',
    ctaLabel: 'Trade Now',
    image: '/images/steps_vector3.svg',
  },
]

export const TRENDING_MARKETS: MarketCoin[] = [
  {
    symbol: 'BTC',
    name: 'Bitcoin',
    pair: 'BTC_USDT',
    icon: '/images/option-img/btc_icon.svg',
    price: '67250.12',
    high: '68100',
    changePct: 2.35,
    favorite: true,
  },
  {
    symbol: 'ETH',
    name: 'Ethereum',
    pair: 'ETH_USDT',
    icon: '/images/wallet_coins_balance.svg',
    price: '3450.45',
    high: '3520',
    changePct: 1.82,
    favorite: true,
  },
  {
    symbol: 'SOL',
    name: 'Solana',
    pair: 'SOL_USDT',
    icon: '/images/option_home_img/sol_currency_vector.svg',
    price: '142.33',
    high: '148.2',
    changePct: 4.12,
    favorite: true,
  },
  {
    symbol: 'BNB',
    name: 'BNB',
    pair: 'BNB_USDT',
    icon: '/images/trade_crypto.svg',
    price: '612.8',
    high: '625',
    changePct: -0.45,
    favorite: false,
  },
  {
    symbol: 'XRP',
    name: 'Ripple',
    pair: 'XRP_USDT',
    icon: '/images/dollaricon.svg',
    price: '0.5234',
    high: '0.54',
    changePct: -1.2,
    favorite: false,
  },
  {
    symbol: 'DOGE',
    name: 'Dogecoin',
    pair: 'DOGE_USDT',
    icon: '/images/bitcoinswap.svg',
    price: '0.1623',
    high: '0.17',
    changePct: 3.1,
    favorite: false,
  },
  {
    symbol: 'ADA',
    name: 'Cardano',
    pair: 'ADA_USDT',
    icon: '/images/trending_icon.svg',
    price: '0.456',
    high: '0.47',
    changePct: 0.88,
    favorite: false,
  },
  {
    symbol: 'AVAX',
    name: 'Avalanche',
    pair: 'AVAX_USDT',
    icon: '/images/trade_icon2.svg',
    price: '36.42',
    high: '37.9',
    changePct: 2.05,
    favorite: false,
  },
  {
    symbol: 'LINK',
    name: 'Chainlink',
    pair: 'LINK_USDT',
    icon: '/images/quick-swap.svg',
    price: '14.22',
    high: '14.8',
    changePct: 5.6,
    favorite: false,
  },
  {
    symbol: 'DOT',
    name: 'Polkadot',
    pair: 'DOT_USDT',
    icon: '/images/trade_arrow.svg',
    price: '7.15',
    high: '7.4',
    changePct: -2.3,
    favorite: false,
  },
  {
    symbol: 'ARB',
    name: 'Arbitrum',
    pair: 'ARB_USDT',
    icon: '/images/trade_vector.svg',
    price: '1.08',
    high: '1.12',
    changePct: 1.5,
    favorite: false,
  },
  {
    symbol: 'OP',
    name: 'Optimism',
    pair: 'OP_USDT',
    icon: '/images/topgainer_icon.svg',
    price: '2.45',
    high: '2.55',
    changePct: -0.8,
    favorite: false,
  },
]

export const ANNOUNCEMENTS: AnnouncementItem[] = [
  {
    id: '1',
    title: 'New trading pairs listed: SOL/USDT',
    time: '2 hours ago',
  },
  {
    id: '2',
    title: 'System maintenance scheduled',
    time: '1 day ago',
  },
]
