import { LegalLayout } from '../LegalLayout.js'

export function AmlPolicyPage() {
  return (
    <LegalLayout
      title="AML Policy"
      lastUpdated="1 January 2025"
      intro="Arab Global Crypto Exchange (AGCE) maintains a comprehensive Anti-Money Laundering (AML) and Counter-Terrorism Financing (CTF) programme in accordance with the requirements of ADGM, VARA, and applicable international standards including FATF Recommendations. This policy outlines the controls we apply to detect, prevent, and report suspicious financial activity."
      sections={[
        {
          heading: 'Customer Due Diligence (CDD)',
          body: 'All AGCE users are subject to Customer Due Diligence procedures. This includes identity verification (KYC), risk classification, and ongoing monitoring of account activity. Enhanced Due Diligence (EDD) is applied to high-risk customers, politically exposed persons (PEPs), and users from high-risk jurisdictions as designated by FATF.',
        },
        {
          heading: 'Transaction Monitoring',
          body: 'AGCE deploys automated transaction monitoring systems to identify unusual or suspicious patterns, including structuring, rapid fund movements, and transactions to or from sanctioned addresses. Our compliance team reviews alerts generated by these systems and escalates confirmed suspicious activity as required.',
        },
        {
          heading: 'Suspicious Activity Reporting',
          body: 'Where reasonable grounds exist to suspect that a transaction is related to money laundering, terrorist financing, or other financial crime, AGCE will file a Suspicious Activity Report (SAR) or Suspicious Transaction Report (STR) with the relevant Financial Intelligence Unit (FIU). Tipping off customers about such reports is strictly prohibited.',
        },
        {
          heading: 'Sanctions Screening',
          body: 'AGCE screens all users and transactions against applicable sanctions lists, including those issued by the UAE, UN, EU, OFAC, and other relevant authorities. Accounts or transactions linked to sanctioned individuals, entities, or jurisdictions are immediately blocked and reported to the relevant authorities.',
        },
      ]}
    />
  )
}
